### ISSUE TITLE
[Exception] throw.Arg_NullReferenceException when click download button

### ISSUE THREAD

**Issue by rosuH** [JuniperPhoton/MyerSplash.UWP#12]
##  Environment Info

OS: Win10 Pro Insider Perview Build 16251_res3_release.170.721-2122
Myersplash: 2.8.2

## Description

- The download button is distored.
- Throw `throws.Arg_NullReferenceExeption` after click download button
- All images can't be download
- Restart app not works.

## Screen capture

![snipaste_20170820_094726](https://user-images.githubusercontent.com/15865017/29491409-b4c0e030-858d-11e7-95ac-854d0ce9eabd.png)

![snipaste_20170820_095614](https://user-images.githubusercontent.com/15865017/29491410-d144cf3c-858d-11e7-9461-d1510c550bef.png)

![gif](https://user-images.githubusercontent.com/15865017/29491443-d9c4e470-858e-11e7-96f6-a3e0620a7ccd.gif)

-----
Thanks.

**Comment by JuniperPhoton** [comment]
Thanks for your feedback.

Is it a sudden issue or you haven’t download the images since you start using this app?

JuniperPhoton
Sent from Polymail

On Sun, 20 Aug 2017 at 9:59 AM rosu <rosu <mailto:rosu%20<notifications@github.com>> > wrote:
Environment Info

OS: Win10 Pro Insider Perview Build 16251_res3_release.170.721-2122
Myersplash: 2.8.2

Description

  *   The download button is distored.
  *   Throw throws.Arg_NullReferenceExeption after click download button
  *   All images can't be download
  *   Restart app not works.

Screen capture

[snipaste_20170820_094726]<https://user-images.githubusercontent.com/15865017/29491409-b4c0e030-858d-11e7-95ac-854d0ce9eabd.png>

[snipaste_20170820_095614]<https://user-images.githubusercontent.com/15865017/29491410-d144cf3c-858d-11e7-9461-d1510c550bef.png>

[snipaste_20170820_095900]<https://user-images.githubusercontent.com/15865017/29491423-369cbe94-858e-11e7-853c-beec4f00efd3.png>

________________________________

Thanks.

**Comment by rosuH** [comment]
@JuniperPhoton  It works fine before. Yes, It happened suddenly.

**Comment by JuniperPhoton** [comment]
I will check this issue later.

**Comment by JuniperPhoton** [comment]
If you hover your mouse to the thumb in list and click the download button, does it occur the same issue?

**Comment by rosuH** [comment]
@JuniperPhoton No, download in list works fine.

**Comment by rosuH** [comment]
Issues disappear after re-install. It seems impossible to reproduce.
