### ISSUE TITLE
[Bug] Lockscreen picture will be replaced with the system default image after reboot

### ISSUE THREAD

**Issue by Mraru** [JuniperPhoton/MyerSplash.UWP#26]
**To Reproduce**:
1. Download picture and choose "Set as both" to use this picture in wallpaper and lockscreen. (Or, MyerSplash will change both wallpaper and lockscreen automatically everyday).
2. Reboot computer.
3. Wallpaper is the same as before, but lockscreen was been changed to the system default image.

**System Info**:
Windows 10 1809, x64

**MyerSplash Info**:
UWP version 3.3.3

I don't know why this happen because MyerSplash works perfect in my months of using. I like this amazing application and thanks to your hardwork!

**Comment by JuniperPhoton** [comment]
Can you post an image showing the changed lockscreen? And also your lockscreen setting page.

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: Mraru <notifications@github.com>
发送时间: 星期五, 十一月 9, 2018 20:00
收件人: JuniperPhoton/MyerSplash.UWP
抄送: Subscribed
主题: [JuniperPhoton/MyerSplash.UWP] [Bug] Lockscreen picture will be replaced with the system default image after reboot (#26)


To Reproduce:

  1.  Download picture and choose "Set as both" to use this picture in wallpaper and lockscreen. (Or, MyerSplash will change both wallpaper and lockscreen automatically everyday).
  2.  Reboot computer.
  3.  Wallpaper is the same as before, but lockscreen was been changed to the system default image.

System Info:
Windows 10 1809, x64

MyerSplash Info:
UWP version 3.3.3

I don't know why this happen because MyerSplash works perfect in my months of using. I like this amazing application and thanks to your hardwork!

―

**Comment by Mraru** [comment]
This is the changed lockscreen:
![Changed.jpg](https://i.loli.net/2018/11/09/5be57bce7d8e9.jpg)

And this is my lockscreen setting:
![SettingPage.jpg](https://i.loli.net/2018/11/09/5be57d8b064bc.jpg)

**Comment by JuniperPhoton** [comment]
Can you do this test: open an image in the built in photo app then set it as lockscreen through the ...  menu?

Try to reboot your computer and see what would happen.

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: Mraru <notifications@github.com>
发送时间: 星期五, 十一月 9, 2018 20:29
收件人: JuniperPhoton/MyerSplash.UWP
抄送: JuniperPhoton; Comment
主题: Re: [JuniperPhoton/MyerSplash.UWP] [Bug] Lockscreen picture will be replaced with the system default image after reboot (#26)


This is the changed lockscreen:
[Changed.jpg]<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2Fe71279acfc824640f13f670098add02f57b97ec1%2F68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f30392f356265353762636537643865392e6a7067&data=02%7C01%7C%7Ced7ed0e176374db5384908d6463f07c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636773633850647846&sdata=eFy10rkxkKmqynbxWv7iAMubaNPNEj0os1S0ooBnbCw%3D&reserved=0>

And this is my lockscreen setting:
[SettingPage.jpg]<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2F2f87fc41ebb2c7fc9af6b5461760b16708903686%2F68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f30392f356265353764386230363462632e6a7067&data=02%7C01%7C%7Ced7ed0e176374db5384908d6463f07c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636773633850647846&sdata=gIUpCtEj4xbgthiAZICDTLcj%2FZpFw6CUGdcPfyJPswM%3D&reserved=0>

―

**Comment by Mraru** [comment]
I set lockscreen via built-in photo app and it works:
![Lockscreen.jpg](https://i.loli.net/2018/11/09/5be580f765e31.jpg)
![PhotoAPP.jpg](https://i.loli.net/2018/11/09/5be580f6cb6aa.jpg)

Then I reboot my computer as usual and... lockscreen doesn't change to the system default one.

**Comment by Mraru** [comment]
Hi developer, I have new info for this problem.

After I did this

> I set lockscreen via built-in photo app and it works

then this problem disappeared. I'm not sure what caused this happen because I did nothing to MyerSplash, but everything look well now. I'll close this issue before this problem occurs again.

**Comment by JuniperPhoton** [comment]
Thanks for your testing.

It seems that this issue belongs to the OS. Nothing can be done currently and I will keep my eyes on that.
